export const DIRTY_QUESTIONS = [
    "Wer würde eher beim Sex einschlafen?",
    "Wer würde eher einen Dreier haben?",
    "Wer würde eher für Geld Nacktfotos verkaufen?",
    "Wer würde eher den Namen des Partners beim Sex verwechseln?",
    "Wer würde eher in der Öffentlichkeit Sex haben?",
    "Wer würde eher eine offene Beziehung führen?",
    "Wer würde eher seinen Partner mit dessen bestem Freund/Freundin betrügen?",
    "Wer würde eher einen peinlichen Fetisch haben?",
    "Wer würde eher beim ersten Date Sex haben?",
    "Wer würde eher heimlich das Handy des Partners durchsuchen?",
    "Wer würde eher einen Porno drehen?",
    "Wer würde eher Sexspielzeug in der Öffentlichkeit benutzen?",
    "Wer würde eher mit dem Ex des besten Freundes/der besten Freundin schlafen?",
    "Wer würde eher beim Sex Socken anlassen?",
    "Wer würde eher jemanden für Sex bezahlen?",
    "Wer würde eher in einem Swingerclub landen?",
    "Wer würde eher beim Vorspiel zu schnell kommen?",
    "Wer würde eher Dirty Talk mit einer albernen Stimme führen?",
    "Wer würde eher eine sexuell übertragbare Krankheit verschweigen?",
    "Wer würde eher einen Kink auf einer Familienfeier ausplaudern?",
    "Wer würde eher mit einem Roboter schlafen?",
    "Wer würde eher beim Sex einen Krampf bekommen?",
    "Wer würde eher einen Orgasmus faken, um nach Hause zu gehen?",
    "Wer würde eher ein sexuelles Rollenspiel mit Kostümen vorschlagen?",
    "Wer würde eher auf einem Trampolin Sex haben?",
    "Wer würde eher aus Versehen die eigenen Eltern beim Sex erwischen?",
    "Wer würde eher beim Sex weinen?",
    "Wer würde eher auf einem Date nur über die eigenen sexuellen Vorlieben reden?",
    "Wer würde eher den Chef anbaggern, um eine Beförderung zu bekommen?",
    "Wer würde eher einen Lapdance von einem Fremden bekommen?",
    "Wer würde eher Sex in einem Flugzeug-WC haben?",
    "Wer würde eher eine Affäre mit einem verheirateten Arbeitskollegen anfangen?",
    "Wer würde eher die Unterwäsche eines Ex-Partners als Trophäe behalten?",
    "Wer würde eher beim Sex laut den falschen Namen rufen?",
    "Wer würde eher eine Beziehung nur wegen gutem Sex weiterführen?",
    "Wer würde eher einen erotischen Roman schreiben?",
    "Wer würde eher betrunken eine peinliche Sex-Nachricht an den falschen Empfänger schicken?",
    "Wer würde eher Analverkehr ausprobieren und es allen erzählen?",
    "Wer würde eher beim Sex gefilmt werden wollen?",
    "Wer würde eher Sex-Tipps von den eigenen Eltern annehmen?",
    "Wer würde eher eine Domina/einen Dominus bezahlen?",
    "Wer würde eher eine peinliche Sex-Panne auf Social Media teilen?",
    "Wer würde eher mit jemandem nur wegen seines Geldes schlafen?",
    "Wer würde eher beim Dirty Talk anfangen zu lachen?",
    "Wer würde eher eine sexuelle Wette eingehen und verlieren?",
    "Wer würde eher auf einer Party Strippoker vorschlagen?",
    "Wer würde eher im Auto der Eltern Sex haben?",
    "Wer würde eher eine peinliche Suchanfrage im Porno-Verlauf haben?",
    "Wer würde eher ein Bordell besuchen?",
    "Wer würde eher Sex-Geräusche machen, die wie ein Tier klingen?",
    "Wer würde eher versuchen, den Partner mit Essen zu verführen und dabei alles versauen?",
    "Wer würde eher in Fesseln schlafen gehen?",
    "Wer würde eher die Jungfräulichkeit an einen viel älteren/jüngeren Partner verlieren?",
    "Wer würde eher einen sexuellen Rekord aufstellen wollen?",
    "Wer würde eher beim Sex einen Anruf der Mutter entgegennehmen?",
    "Wer würde eher Sex-Träume von einem Freund/einer Freundin haben und es beichten?",
    "Wer würde eher eine Geschlechtskrankheit für einen Ausschlag halten?",
    "Wer würde eher einen Futanari-Charakter daten?",
    "Wer würde eher heimlich auf den OnlyFans-Account eines Bekannten stoßen?",
    "Wer würde eher beim Sex anfangen, über Politik zu diskutieren?",
    "Wer würde eher einen Kink für Füße entwickeln?",
    "Wer würde eher eine Affäre mit dem Postboten haben?",
    "Wer würde eher ein Nackt-Selfie an die ganze Familie schicken?",
    "Wer würde eher beim Sex die Zähne nicht putzen?",
    "Wer würde eher einen Porno-Star daten?",
    "Wer würde eher beim Vorspiel pupsen?",
    "Wer würde eher die sexuellen Vorlieben des Partners googeln?",
    "Wer würde eher auf einer öffentlichen Toilette masturbieren?",
    "Wer würde eher beim Sex über den Ex reden?",
    "Wer würde eher ein Date wegen schlechtem Küssen verlassen?",
    "Wer würde eher eine geheime Sammlung von Sexspielzeug haben?",
    "Wer würde eher beim Sex komische Essensgelüste bekommen?",
    "Wer würde eher einen Quickie im Büro haben?",
    "Wer würde eher eine Sex-Playlist mit peinlichen Songs erstellen?",
    "Wer würde eher auf BDSM-Partys gehen?",
    "Wer würde eher ein erotisches Gedicht für den Partner schreiben?",
    "Wer würde eher eine Person abschleppen, die aussieht wie der eigene Vater/die eigene Mutter?",
    "Wer würde eher beim Sex einschlafen und schnarchen?",
    "Wer würde eher die Zahnbürste des Partners als Sexspielzeug benutzen?",
    "Wer würde eher eine Wette verlieren und nackt durch die Stadt laufen?",
    "Wer würde eher beim Sex die ganze Zeit Augenkontakt halten, ohne zu blinzeln?",
    "Wer würde eher einen Striptease vorführen und dabei hinfallen?",
    "Wer würde eher Sex in einem Beichtstuhl haben?",
    "Wer würde eher einen Liebesbrief an sich selbst schreiben?",
    "Wer würde eher eine Affäre mit einer künstlichen Intelligenz haben?",
    "Wer würde eher beim Sex die Nationalhymne singen?",
    "Wer würde eher versuchen, sexy zu tanzen und dabei wie ein Huhn auszusehen?",
    "Wer würde eher einen Partner mit einem peinlichen Spitznamen im Bett nennen?",
    "Wer würde eher eine Nacht im Gefängnis verbringen, weil er/sie in der Öffentlichkeit erwischt wurde?",
    "Wer würde eher die Kreditkarte des Partners für teure Dessous belasten?",
    "Wer würde eher beim Sex eine Sportverletzung erleiden?",
    "Wer würde eher eine sexuelle Fantasie mit Legosteinen haben?",
    "Wer würde eher den eigenen Therapeuten anmachen?",
    "Wer würde eher beim Sex so laut sein, dass die Nachbarn anrufen?",
    "Wer würde eher eine Beziehung per SMS beenden, direkt nach dem Sex?",
    "Wer würde eher Kondome mit merkwürdigem Geschmack kaufen?",
    "Wer würde eher beim Sex auf die falsche Person rollen?",
    "Wer würde eher eine sexuelle Erfahrung erfinden, um anzugeben?",
    "Wer würde eher einen Anmachspruch aus einem Porno im echten Leben verwenden?",
    "Wer würde eher ein Sex-Tagebuch führen und es verlieren?",
    "Wer würde eher eine erotische Massage anbieten und dabei Öl verschütten?",
    "Wer würde eher auf einer Hochzeit mit einem der Brautjungfern/Trauzeugen rummachen?",
    "Wer würde eher das Safeword vergessen?",
    "Wer würde eher im Schlaf reden und dabei sexuelle Geheimnisse verraten?",
    "Wer würde eher eine heimliche sexuelle Identität haben?",
    "Wer würde eher einen Fetisch für Uniformen haben?",
    "Wer würde eher beim Sex weglaufen?",
    "Wer würde eher einen Porno nachsynchronisieren?",
    "Wer würde eher Viagra ausprobieren, nur um zu sehen, was passiert?",
    "Wer würde eher einen Freund/eine Freundin über eine Dating-App für einen Dreier suchen?",
    "Wer würde eher beim Höhepunkt lachen?",
    "Wer würde eher eine Orgie organisieren?",
    "Wer würde eher einen Stöhnen-Wettbewerb veranstalten?",
    "Wer würde eher auf einem Friedhof Sex haben?",
    "Wer würde eher eine Affäre mit dem Partner des Chefs haben?",
    "Wer würde eher Nacktbilder von sich im Internet finden?",
    "Wer würde eher einen Kuss auf dem ersten Date erzwingen?",
    "Wer würde eher die sexuellen Fähigkeiten eines Freundes bewerten?",
    "Wer würde eher eine sexuelle Begegnung mit einem Alien haben wollen?",
    "Wer würde eher beim Sex anfangen zu beatboxen?",
    "Wer würde eher eine Sexpuppe kaufen und sie wie einen Ex-Partner benennen?",
    "Wer würde eher einen sexuellen Akt in einem Kochrezept verstecken?",
    "Wer würde eher eine Peitsche als modisches Accessoire tragen?",
    "Wer würde eher beim Petting einschlafen?",
    "Wer würde eher auf Tinder ein Bild vom eigenen Haustier hochladen und 'suche Spielkameraden' schreiben?",
    "Wer würde eher einen Raum voller Menschen fragen, ob sie auf 'Golden Showers' stehen?",
    "Wer würde eher versuchen, mit den Füßen einen Orgasmus zu bekommen?",
    "Wer würde eher eine erotische Fan-Fiction über die Leute in diesem Raum schreiben?",
    "Wer würde eher beim Sex eine To-Do-Liste im Kopf durchgehen?",
    "Wer würde eher einen Pornosprecher als Navi-Stimme einstellen?",
    "Wer würde eher beim Sex fragen: 'Bist du schon fertig?'",
    "Wer würde eher das Bett nach dem Sex nie frisch beziehen?",
    "Wer würde eher einen sexuellen Fetisch für Gartenzwerge entwickeln?",
    "Wer würde eher eine Beziehung führen, nur um regelmäßigen Sex zu haben?",
    "Wer würde eher einen Stripclub erben und weiterführen?",
    "Wer würde eher einen Liebesbiss an einer peinlichen Stelle hinterlassen?",
    "Wer würde eher auf einer Familienfeier über die eigenen sexuellen Eroberungen prahlen?",
    "Wer würde eher Gleitgel als Haargel verwenden?",
    "Wer würde eher einen Fremden fragen, welche Unterwäsche er/sie trägt?",
    "Wer würde eher eine sexuelle Wette abschließen und dabei den Einsatz immer weiter erhöhen?",
    "Wer würde eher eine Affäre mit dem eigenen Cousin/der eigenen Cousine haben?",
    "Wer würde eher einen Porno mit den eigenen Großeltern als Hauptdarsteller sehen wollen?",
    "Wer würde eher beim Sex die falsche Öffnung erwischen?",
    "Wer würde eher einen erotischen Kalender mit sich selbst als Model erstellen?",
    "Wer würde eher beim Online-Dating lügen und behaupten, ein Sex-Gott zu sein?",
    "Wer würde eher die Unterwäsche eines Mitbewohners anprobieren?",
    "Wer würde eher während einer wichtigen Präsentation an Sex denken?",
    "Wer würde eher eine Sex-Schaukel im Wohnzimmer aufhängen?",
    "Wer würde eher eine geheime Identität als Cam-Girl/Boy haben?",
    "Wer würde eher den Partner bitten, sich als Cartoon-Figur zu verkleiden?",
    "Wer würde eher beim Vorspiel eine Anleitung von YouTube befolgen?",
    "Wer würde eher Sex-Geräusche faken, um die Nachbarn zu ärgern?"
];
